### PR TITLE
use icons for the vertical ellipsis

### PR DESCRIPTION
**Pull request by jeromedockes**
- use icons for the "..." to make sure they are clearly visible regardless of the font
- make the dashed line darker (another option would be to make it wider)
- minor change in css so we don't need to have the "ellided-table-part" class on the td, on the tbody is enough

### CODE REVIEW

**Comment by GaelVaroquaux** [comment]
I wonder if it's not strange to have the lines a bit too dark. Depending on my screen I find it strange or not.

If you think it's not strange, I'll merge

**Comment by jeromedockes** [comment]
ok how about making them wider instead?

screenshot_2024-09-24T10:09:30+02:00

**Comment by jeromedockes** [comment]
otherwise keeping the outside borders solid as you had before is also fine. I pushed a commit doing that, so you can pick between the last 3 commits on this branch all are ok for me.

the last commit is basically what you had in the original pr except that the vertical "..." are more visible

**Comment by GaelVaroquaux** [comment]
Thanks, merging!!

**Pull request merged**
